#! /bin/sh

# xrandr
xrandr --output DP-4 --mode 1920x1080 --rate 165


# wallpaper
feh --no-fehbg --bg-scale $HOME/.config/bspwm/backgrounds/plane.png 

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.50

bspc config focused_border_color "#f38ba8"
bspc config normal_border_color "#575268"
bspc config active_border_color "#F5E0DC"

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config single_monocle        false

# fix pointer
xsetroot -cursor_name left_ptr

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst nm-applet ksuperkey xfce4-power-manager

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Launch NetworkManager applet
nm-applet &

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --experimental-backends &

# Java applications
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1


# rsync
rsync -var /home/rex/.config /home/rex/.backups&&rsync -var /home/rex/.minecraft /home/rex/.backups&&rsync -var /home/rex/.mine-server /home/rex/.backups

# gnome-keyring
gnome-keyring-daemon -s & xdo raise -N Polybar


$HOME/.config/bspwm/polybar/launch.sh
